<?php

declare(strict_types=1);

namespace Database\Seeders;

use DateTimeImmutable;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seed the `admin_config` table with platform defaults.
 *
 * These values are read by engines during boot and cache-layered.
 * All internal keys are snake_case, never magic numbers in domain code.
 *
 * Ref: docs/engines/rp-economy/, docs/engines/challenge/, docs/engines/season/, etc.
 */
class AdminConfigSeeder extends Seeder
{
    public function run(): void
    {
        $now = (new DateTimeImmutable('now', timezone_open('UTC')))->format('Y-m-d H:i:s');

        $this->seedMissing($now, [
            // RP Economy defaults
            [
                'key' => 'rp.win',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '10',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: RP awarded for match win',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'rp.draw',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '5',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: RP awarded for draw',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'rp.loss',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '1',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: RP awarded for match loss',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Challenge Engine defaults
            [
                'key' => 'challenge.min_rp_to_issue',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '50',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: Minimum RP required to issue a challenge',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'challenge.response_window_hours',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '72',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Hours for challenge response (3 days)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'challenge.scheduling_window_days',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '4',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Days to schedule after acceptance',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'challenge.stood_ground_cost_percent',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '0.25',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: RP cost as % of challenged stake if draw',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Match / Fixture defaults
            [
                'key' => 'match.default_duration_minutes',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '90',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Default match duration',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Season defaults
            [
                'key' => 'season.start_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '4',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: Season starts April 1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.end_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: Season ends Feb 28/29',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.start_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '1',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: Season starts on day 1 of start_month',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.end_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '31',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: end_day acts as a ceiling; SeasonCalendar clamps to last valid day (Feb 28/29 leap-aware)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.peak_months',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '[12,1]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Peak months Dec/Jan (JSON array of month ints)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.participation_cutoff_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '7',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Participation cutoff month (July)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.participation_cutoff_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '31',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Participation cutoff day (Jul 31)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.closing_window_end_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '14',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Closing window ends Mar 14',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.archive_window_end_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '31',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Archive window ends Mar 31',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.new_ranked_challenge_cutoff_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No new ranked challenges after Feb 7',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.new_ranked_challenge_cutoff_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '7',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No new ranked challenges after Feb 7',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.ranked_acceptance_cutoff_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No ranked acceptances after Feb 14',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.ranked_acceptance_cutoff_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '14',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No ranked acceptances after Feb 14',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Notification & Distribution
            [
                'key' => 'notification.whatsapp_quiet_start_hour',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '22',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Start quiet hours (10 PM)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'notification.whatsapp_quiet_end_hour',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '7',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: End quiet hours (7 AM)',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Booking & Venue
            [
                'key' => 'booking.hold_ttl_minutes',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '30',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: Hold expiry on booking (30 min)',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Moderation defaults
            [
                'key' => 'moderation.auto_hold_keywords',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '[]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Empty keyword list for auto-screening',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Zone Engine defaults
            [
                'key' => 'zone.area_suggestion_enabled',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => 'true',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: Allow users to submit Area suggestions',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'zone.area_suggestion_min_name_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '3',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Minimum length of proposed_name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'zone.area_suggestion_max_name_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '80',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Maximum length of proposed_name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'zone.throttle.read.per_minute',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '60',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: per-IP rate for public Zone reads (hubs/areas)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'zone.throttle.suggest.per_minute',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '5',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: per-user rate for area-suggestion submission',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Identity Engine — profile + avatar + public profile defaults
            [
                'key' => 'users.profile.name_min',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Minimum display name length',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'users.profile.name_max',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '60',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Maximum display name length',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'users.avatar.driver',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => 'local',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: Default avatar storage driver',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'users.avatar.max_bytes',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2097152',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Avatar maximum size (2 MiB)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'users.avatar.allowed_mime',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode(['image/jpeg', 'image/png', 'image/webp']),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Allowed avatar MIME types',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'users.avatar.throttle.per_minute',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '10',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Avatar upload rate limit per user',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Player & Affiliation engine — profile-form vocabulary + bounds.
            // Engine doc §3, §6, §12. Registered so an admin can change an option
            // set, a label, or a bound without a deploy (Constitution Law 2/4).
            // Served to clients by GET /api/v1/players/meta (ADR-0007).
            [
                'key' => 'player.positions',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'goalkeeper',
                    'left_back', 'centre_back', 'right_back',
                    'defensive_midfielder',
                    'left_midfielder', 'centre_midfielder', 'right_midfielder',
                    'attacking_midfielder',
                    'left_winger', 'right_winger',
                    'second_striker', 'striker',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: allowed primary-position keys, back-to-front order',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.positions.labels',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'goalkeeper' => 'Goalkeeper',
                    'left_back' => 'Left Back',
                    'centre_back' => 'Centre Back',
                    'right_back' => 'Right Back',
                    'defensive_midfielder' => 'Defensive Midfielder',
                    'left_midfielder' => 'Left Midfielder',
                    'centre_midfielder' => 'Centre Midfielder',
                    'right_midfielder' => 'Right Midfielder',
                    'attacking_midfielder' => 'Attacking Midfielder',
                    'left_winger' => 'Left Winger',
                    'right_winger' => 'Right Winger',
                    'second_striker' => 'Second Striker',
                    'striker' => 'Striker',
                    // Retired keys. NOT in `player.positions`, so nobody can pick
                    // them, but players who chose one before 2026-08-19 still have
                    // it stored. Labels are a lookup, not an option set: keeping
                    // these stops an old profile rendering the raw key at people.
                    'defender' => 'Defender',
                    'midfielder' => 'Midfielder',
                    'forward' => 'Forward',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: display labels for primary positions',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.positions.abbreviations',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'goalkeeper' => 'GK',
                    'left_back' => 'LB',
                    'centre_back' => 'CB',
                    'right_back' => 'RB',
                    'defensive_midfielder' => 'DM',
                    'left_midfielder' => 'LM',
                    'centre_midfielder' => 'CM',
                    'right_midfielder' => 'RM',
                    'attacking_midfielder' => 'AM',
                    'left_winger' => 'LW',
                    'right_winger' => 'RW',
                    'second_striker' => 'SS',
                    'striker' => 'ST',
                    // Retired keys, kept for the same reason as the labels above.
                    'defender' => 'DF',
                    'midfielder' => 'MF',
                    'forward' => 'FW',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: short forms drawn on the pitch picker',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.positions.descriptions',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'goalkeeper' => 'You keep the ball out of the net.',
                    'left_back' => 'You defend the left side and help the attack.',
                    'centre_back' => 'You defend the middle and win headers.',
                    'right_back' => 'You defend the right side and help the attack.',
                    'defensive_midfielder' => 'You sit in front of the defence and win the ball.',
                    'left_midfielder' => 'You run the left side, back and forward.',
                    'centre_midfielder' => 'You run the middle and set the pace.',
                    'right_midfielder' => 'You run the right side, back and forward.',
                    'attacking_midfielder' => 'You create the chances.',
                    'left_winger' => 'You take players on down the left.',
                    'right_winger' => 'You take players on down the right.',
                    'second_striker' => 'You play just behind the striker.',
                    'striker' => 'You score the goals.',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: one-line explanation per position',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.availability.default',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => 'unknown',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: availability preselected when the player omits one',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.availability.labels',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'available' => 'Available to play',
                    'limited' => 'Available with notice',
                    'unavailable' => 'Not available',
                    'unknown' => 'Not sure yet',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: display labels for availability states',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.availability.descriptions',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'available' => 'Clubs building a squad will see you as ready.',
                    'limited' => 'You will show as playable, with notice needed.',
                    'unavailable' => 'You stay on the register but out of squad shortlists.',
                    'unknown' => 'You can set this any time from your profile.',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: consequence copy shown under each availability option',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.market_status.labels',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'free_agent' => 'Free agent',
                    'affiliated' => 'Affiliated',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: display labels for football market status',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.card_confidence.tiers',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    ['key' => 'provisional', 'min_confirmed_matches' => 0],
                    ['key' => 'growing', 'min_confirmed_matches' => 3],
                    ['key' => 'verified', 'min_confirmed_matches' => 10],
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: card-confidence ladder (engine doc §14) in place of a numeric rating',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.card_confidence.labels',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([
                    'provisional' => 'Provisional',
                    'growing' => 'Growing',
                    'verified' => 'Verified',
                ]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: display labels for the card-confidence tiers',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.profile.name_max_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '80',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: max length of first/last name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.profile.stage_name_max_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '40',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: max length of the stage/jersey name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.profile.preferred_number_min',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '1',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: lowest allowed preferred shirt number',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.profile.preferred_number_max',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '99',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: highest allowed preferred shirt number',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.profile.preferred_number_quick_picks',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => json_encode([1, 4, 6, 7, 8, 9, 10, 11]),
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: one-tap shirt numbers offered at profile setup',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.profile.create.throttle.per_minute',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '5',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: profile-creation rate limit per user',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.throttle.read.per_minute',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '60',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: player vocabulary read rate limit per IP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'player.meta.cache_ttl_seconds',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '300',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Cache-Control max-age for the player vocabulary read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'users.public_profile.throttle.anonymous_per_minute',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '60',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Public profile lookup rate limit',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Club engine - creation vocabulary + the reserved-name policy.
            // WP-20260823-club-creation. Contracts: contracts/config/club/*.yaml.
            [
                'key' => 'club.tiers',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '["amateur", "professional"]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: the two doors at club creation (ADR-0017)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.tiers.labels',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '{"amateur": "Amateur", "professional": "Professional"}',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: tier display labels',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.tiers.descriptions',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '{"amateur": "Friends, a community side, a school or work team.", "professional": "A registered club or academy. We check before it goes live."}',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: one line under each tier',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.types',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '["community", "informal", "school", "academy", "corporate", "religious", "institution", "facility", "registered"]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: allowed club-type keys (engine doc 3)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.types.tier',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '{"community": "amateur", "informal": "amateur", "school": "amateur", "corporate": "amateur", "religious": "amateur", "facility": "amateur", "academy": "professional", "institution": "professional", "registered": "professional"}',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: which tier each club type belongs to',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.types.labels',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '{"community": "Community club", "informal": "Friends or crew", "school": "School team", "academy": "Academy", "corporate": "Workplace team", "religious": "Church or mosque team", "institution": "Institution team", "facility": "Facility team", "registered": "Registered club"}',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: club-type display labels (replaces the hardcoded CLUB_TYPE_LABELS)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.types.descriptions',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '{"community": "An area or neighbourhood team.", "informal": "A group of friends who play under one name.", "school": "A school, class or campus team.", "academy": "A training club with youth squads.", "corporate": "A company or office team.", "religious": "A church or mosque team.", "institution": "A university, NGO or association team.", "facility": "A team based at one pitch.", "registered": "A club with papers or official backing."}',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: one line under each club type',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.name.reserved_terms',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '[{"canonical": "Asante Kotoko", "aliases": ["kotoko", "porcupine warriors"]}, {"canonical": "Hearts of Oak", "aliases": ["accra hearts of oak", "phobia"]}, {"canonical": "Aduana Stars", "aliases": ["aduana"]}, {"canonical": "Medeama", "aliases": ["medeama sporting"]}, {"canonical": "Karela United", "aliases": ["karela"]}, {"canonical": "Nations FC", "aliases": []}, {"canonical": "Bofoakwa Tano", "aliases": ["bofoakwa"]}, {"canonical": "Real Tamale United", "aliases": ["rtu"]}, {"canonical": "Tamale City", "aliases": []}, {"canonical": "Manchester United", "aliases": ["man united", "man utd", "manchester utd", "red devils"]}, {"canonical": "Manchester City", "aliases": ["man city"]}, {"canonical": "Liverpool", "aliases": ["the reds"]}, {"canonical": "Chelsea", "aliases": ["the blues"]}, {"canonical": "Arsenal", "aliases": ["the gunners"]}, {"canonical": "Barcelona", "aliases": ["barca"]}, {"canonical": "Real Madrid", "aliases": []}, {"canonical": "Bayern Munich", "aliases": ["bayern munchen"]}, {"canonical": "Juventus", "aliases": ["juve"]}, {"canonical": "Paris Saint Germain", "aliases": ["psg"]}]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: club names an amateur club may not take (ADR-0017)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.name.ignored_tokens',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '["fc", "f.c.", "sc", "afc", "football", "club", "team"]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: generic words dropped before matching a reserved name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.profile.name_min_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: shortest club name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.profile.name_max_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '120',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: longest club name (clubs.name column ceiling)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.meta.cache_ttl_seconds',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '300',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: max-age on GET /clubs/meta',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Club crest upload. WP-20260823-club-creation.
            [
                'key' => 'club.media.driver',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => 'local',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: where club crests are stored (local | r2)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.media.r2.public_url',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: public base URL for crests when driver=r2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.media.max_kilobytes',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '5120',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: largest crest upload in KB',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.media.allowed_extensions',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '["jpg", "jpeg", "png", "webp"]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: crest image types (no SVG - it can carry script)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'club.media.throttle.per_minute',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '10',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: crest uploads per minute per user',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    /**
     * Insert only the keys that do not exist yet.
     *
     * NOT `insertOrIgnore`. The unique index on `admin_config` is
     * (key, scope, scope_id, effective_from), and `effective_from` is set to
     * "now" on every run, so no two runs ever collide and nothing was ever
     * ignored. Running this seeder twice therefore inserted a complete second
     * copy of every key, and a local database had accumulated 190 rows for 53
     * keys before anyone noticed. Reads still worked, which is exactly why it
     * went unnoticed: `Config::get` takes the newest row and the copies were
     * identical.
     *
     * Existence is checked on (key, scope, scope_id) alone, deliberately
     * ignoring version and value. A key that already exists may have been
     * changed by an admin since it was seeded, and a seeder must never
     * overwrite a governed decision. Changing the value of a key that already
     * ships is a migration's job, not this one's: see
     * `2026_08_19_000001_expand_player_positions_config`.
     *
     * That makes this safe to run on every deploy, which is the point.
     *
     * @param  list<array<string, mixed>>  $rows
     */
    private function seedMissing(string $now, array $rows): void
    {
        $existing = DB::table('admin_config')
            ->select('key', 'scope', 'scope_id')
            ->get()
            ->map(static fn (object $row): string => $row->key.'|'.$row->scope.'|'.($row->scope_id ?? ''))
            ->flip();

        $missing = array_values(array_filter(
            $rows,
            static fn (array $row): bool => ! $existing->has(
                $row['key'].'|'.$row['scope'].'|'.($row['scope_id'] ?? ''),
            ),
        ));

        if ($missing === []) {
            $this->command?->info('admin_config: already complete, nothing to seed.');

            return;
        }

        DB::table('admin_config')->insert($missing);

        $this->command?->info(sprintf(
            'admin_config: seeded %d new key(s): %s',
            count($missing),
            implode(', ', array_column($missing, 'key')),
        ));
    }
}
