<?php

declare(strict_types=1);

namespace Database\Seeders;

use DateTimeImmutable;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seed the `admin_config` table with platform defaults.
 *
 * These values are read by engines during boot and cache-layered.
 * All internal keys are snake_case, never magic numbers in domain code.
 *
 * Ref: docs/engines/rp-economy/, docs/engines/challenge/, docs/engines/season/, etc.
 */
class AdminConfigSeeder extends Seeder
{
    public function run(): void
    {
        $now = (new DateTimeImmutable('now', timezone_open('UTC')))->format('Y-m-d H:i:s');

        DB::table('admin_config')->insertOrIgnore([
            // RP Economy defaults
            [
                'key' => 'rp.win',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '10',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: RP awarded for match win',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'rp.draw',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '5',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: RP awarded for draw',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'rp.loss',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '1',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: RP awarded for match loss',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Challenge Engine defaults
            [
                'key' => 'challenge.min_rp_to_issue',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '50',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: Minimum RP required to issue a challenge',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'challenge.response_window_hours',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '72',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Hours for challenge response (3 days)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'challenge.scheduling_window_days',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '4',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Days to schedule after acceptance',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'challenge.stood_ground_cost_percent',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '0.25',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: RP cost as % of challenged stake if draw',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Match / Fixture defaults
            [
                'key' => 'match.default_duration_minutes',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '90',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Default match duration',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Season defaults
            [
                'key' => 'season.start_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '4',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: Season starts April 1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.end_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: Season ends Feb 28/29',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.start_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '1',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: Season starts on day 1 of start_month',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.end_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '31',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'critical',
                'change_reason' => 'Initial seed: end_day acts as a ceiling; SeasonCalendar clamps to last valid day (Feb 28/29 leap-aware)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.peak_months',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '[12,1]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Peak months Dec/Jan (JSON array of month ints)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.participation_cutoff_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '7',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Participation cutoff month (July)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.participation_cutoff_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '31',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Participation cutoff day (Jul 31)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.closing_window_end_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '14',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Closing window ends Mar 14',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.archive_window_end_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '31',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Archive window ends Mar 31',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.new_ranked_challenge_cutoff_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No new ranked challenges after Feb 7',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.new_ranked_challenge_cutoff_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '7',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No new ranked challenges after Feb 7',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.ranked_acceptance_cutoff_month',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '2',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No ranked acceptances after Feb 14',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'season.ranked_acceptance_cutoff_day',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '14',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: No ranked acceptances after Feb 14',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Notification & Distribution
            [
                'key' => 'notification.whatsapp_quiet_start_hour',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '22',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Start quiet hours (10 PM)',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'notification.whatsapp_quiet_end_hour',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '7',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: End quiet hours (7 AM)',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Booking & Venue
            [
                'key' => 'booking.hold_ttl_minutes',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '30',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: Hold expiry on booking (30 min)',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Moderation defaults
            [
                'key' => 'moderation.auto_hold_keywords',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '[]',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'high',
                'change_reason' => 'Initial seed: Empty keyword list for auto-screening',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Zone Engine defaults
            [
                'key' => 'zone.area_suggestion_enabled',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => 'true',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'medium',
                'change_reason' => 'Initial seed: Allow users to submit Area suggestions',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'zone.area_suggestion_min_name_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '3',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Minimum length of proposed_name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'zone.area_suggestion_max_name_length',
                'scope' => 'platform',
                'scope_id' => null,
                'value' => '80',
                'effective_from' => $now,
                'version' => 1,
                'approval_level' => 'low',
                'change_reason' => 'Initial seed: Maximum length of proposed_name',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
