<?php

declare(strict_types=1);

namespace Database\Seeders;

use DateTimeImmutable;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Ghana geography for the Zone engine: the regional capitals as City Hubs, and
 * the localities under them as Areas.
 *
 * GENERATED by kalaanba-front/scripts/build-geography-seeder.mjs from data
 * sourced through Google (Geocoding for the cities, Places for the localities)
 * and then reviewed. Regenerate rather than hand-edit, and re-read the diff:
 * this is admin-controlled reference data (Zone engine 2/5) and a name that
 * lands here becomes somewhere a player calls home.
 *
 * WHAT GOOGLE COULD AND COULD NOT DO. Cities resolved perfectly: canonical
 * name, region and centre for all thirteen. Localities did not. Coverage
 * tracks city size, so Accra and Kumasi are well mapped while Tamale, the
 * launch market, is barely mapped at all. Hard-restricted to 25km and filtered
 * to geographic types, 8 of 10 of the names in PRODUCT.md 11 return NOTHING,
 * and unfiltered they return the landmarks inside them: "Lamashegu Police
 * Station Round-about", "Kalpohin SHS", "Aboabo Market". Tamale's list is
 * therefore the product's own, from PRODUCT.md 11 and the Zone doc examples.
 * Four hubs have no Areas at all; the suggestion flow (5) is how they fill.
 *
 * EXPANDED 2026-08-23 (WP-20260823-club-creation). Tamale went from 17 Areas
 * to 44: a club being created could not find the area it plays from, which is
 * the launch market failing at the first question that matters. Re-running
 * Google would not have helped and was not attempted again; the finding above
 * still holds. The additions are Tamale Metropolitan and Sagnarigu
 * neighbourhoods and they need a local review before they are trusted: a name
 * that lands here becomes somewhere a player calls home.
 *
 * ZONES ARE PROVISIONAL. The Zone doc defines a Zone as a competitive division
 * and an Area as the locality a club represents, while PRODUCT.md 11 lists
 * Tamale's eight localities under the heading "Zones". Which localities group
 * into which division is a football decision an admin makes, not one a seeder
 * should invent, so every Area lands under a single '<City> Central' zone for
 * an admin to remap ("request Area/Zone changes"). Flagged for the Engine
 * Owner.
 *
 * Idempotent: deterministic UUIDv5 ids and insertOrIgnore, so re-running is a
 * no-op and existing rows keep the ids other tables already reference.
 */
class GhanaGeographySeeder extends Seeder
{
    /** Namespace for deterministic ids. Changing it re-keys the whole tree. */
    private const NAMESPACE_UUID = '6ba7b810-9dad-11d1-80b4-00c04fd430c8';

    /** Ghana, as seeded by ZoneHierarchySeeder. Reused so the two agree. */
    private const COUNTRY_ID = '8c2f9d0a-2c5b-4e3e-9c1e-6a3b1a0e1001';

    public function run(): void
    {
        $now = (new DateTimeImmutable('now', timezone_open('UTC')))->format('Y-m-d H:i:s');

        DB::table('countries')->insertOrIgnore([
            'id' => self::COUNTRY_ID,
            'code' => 'GH',
            'name' => 'Ghana',
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        foreach ($this->hubs() as $hub) {
            $regionCode = $this->slug($hub['region']);
            $regionId = $hub['region_id'] ?? $this->uuid5('region:'.$regionCode);

            DB::table('regions')->insertOrIgnore([
                'id' => $regionId,
                'country_id' => self::COUNTRY_ID,
                'code' => $regionCode,
                'name' => $hub['region'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            $hubId = $hub['hub_id'] ?? $this->uuid5('hub:'.$hub['code']);
            DB::table('city_hubs')->insertOrIgnore([
                'id' => $hubId,
                'region_id' => $regionId,
                'code' => $hub['code'],
                'name' => $hub['name'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            // One provisional division per hub. See the note above.
            $zoneCode = $hub['zone_code'] ?? $this->slug($hub['name']).'-central';
            $zoneId = $hub['zone_id'] ?? $this->uuid5('zone:'.$zoneCode);
            DB::table('zones')->insertOrIgnore([
                'id' => $zoneId,
                'city_hub_id' => $hubId,
                'kind' => 'zone',
                'code' => $zoneCode,
                'name' => $hub['zone_name'] ?? $hub['name'].' Central',
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            foreach ($hub['areas'] as $areaName) {
                $areaCode = $this->slug($areaName);
                DB::table('areas')->insertOrIgnore([
                    'id' => $this->uuid5('area:'.$hub['code'].':'.$areaCode),
                    'zone_id' => $zoneId,
                    'code' => $areaCode,
                    'name' => $areaName,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }

    /**
     * @return list<array{name: string, code: string, region: string, hub_id: ?string, zone_id: ?string, zone_code: ?string, zone_name: ?string, areas: list<string>}>
     */
    private function hubs(): array
    {
        return [
            [
                'name' => 'Tamale',
                'code' => 'TML',
                'region' => 'Northern Region',
                'region_id' => '8c2f9d0a-2c5b-4e3e-9c1e-6a3b1a0e1002',
                'hub_id' => '8c2f9d0a-2c5b-4e3e-9c1e-6a3b1a0e1003',
                'zone_id' => '8c2f9d0a-2c5b-4e3e-9c1e-6a3b1a0e1004',
                'zone_code' => 'tml-central',
                'zone_name' => 'Tamale Central',
                'areas' => [
                    'Aboabo',
                    'Bagabaga',
                    'Banvim',
                    'Bulpela',
                    'Changli',
                    'Checko',
                    'Choggu',
                    'Dabokpa',
                    'Datoyili',
                    'Dungu',
                    'Education Ridge',
                    'Fuo',
                    'Gumani',
                    'Gumbihini',
                    'Gurugu',
                    'Jakariyili',
                    'Jisonayili',
                    'Kalariga',
                    'Kalpohin',
                    'Kanvile',
                    'Kasalgo',
                    'Kpalsi',
                    'Kpanvo',
                    'Kukuo',
                    'Lamashegu',
                    'Malshegu',
                    'Moshie Zongo',
                    'NORRIP Village',
                    'Nyanshegu',
                    'Nyohini',
                    'Russian Bungalow',
                    'Sagnarigu',
                    'Sakasaka',
                    'Shishegu',
                    'Sognaayili',
                    'Taha',
                    'Tishigu',
                    'Tutingli',
                    'Vittin',
                    'Warizehi',
                    'Waterworks',
                    'Yapalsi',
                    'Zogbeli',
                    'Zujung',
                ],
            ],
            [
                'name' => 'Accra',
                'code' => 'accra',
                'region' => 'Greater Accra Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Abeka',
                    'Accra New Town',
                    'Adabraka',
                    'Airport Residential Area',
                    'Alajo',
                    'Christian Village',
                    'Dansoman',
                    'Kaneshie',
                    'Maamobi',
                    'Mamprobi',
                    'North Industrial Area',
                    'Osu',
                ],
            ],
            [
                'name' => 'Kumasi',
                'code' => 'kumasi',
                'region' => 'Ashanti Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Ahodwo',
                    'Amakom',
                    'Asafo',
                    'Asokore Mampong',
                    'Bantama',
                    'Fumesua',
                    'Kaase',
                    'Kotei',
                    'Kwadaso',
                    'Mamponteng',
                    'Santasi',
                    'Tanoso',
                ],
            ],
            [
                'name' => 'Takoradi',
                'code' => 'takoradi',
                'region' => 'Western Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Diabene',
                    'Effia Kuma',
                    'Fijai',
                    'West Tanokrom',
                ],
            ],
            [
                'name' => 'Tema',
                'code' => 'tema',
                'region' => 'Greater Accra Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Tema New Town',
                ],
            ],
            [
                'name' => 'Cape Coast',
                'code' => 'cape-coast',
                'region' => 'Central Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [],
            ],
            [
                'name' => 'Sunyani',
                'code' => 'sunyani',
                'region' => 'Bono Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [],
            ],
            [
                'name' => 'Koforidua',
                'code' => 'koforidua',
                'region' => 'Eastern Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Koforidua Central Business District',
                    'Okorase',
                    'Oyoko',
                    'Suhyen',
                ],
            ],
            [
                'name' => 'Ho',
                'code' => 'ho',
                'region' => 'Volta Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [],
            ],
            [
                'name' => 'Wa',
                'code' => 'wa',
                'region' => 'Upper West Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [],
            ],
            [
                'name' => 'Bolgatanga',
                'code' => 'bolgatanga',
                'region' => 'Upper East Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Bukere',
                ],
            ],
            [
                'name' => 'Techiman',
                'code' => 'techiman',
                'region' => 'Bono East Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Aturunsa',
                    'Tanoso',
                ],
            ],
            [
                'name' => 'Obuasi',
                'code' => 'obuasi',
                'region' => 'Ashanti Region',
                'region_id' => null,
                'hub_id' => null,
                'zone_id' => null,
                'zone_code' => null,
                'zone_name' => null,
                'areas' => [
                    'Kokoteasua',
                    'Memrewa',
                ],
            ],
        ];
    }

    private function slug(string $value): string
    {
        $slug = strtolower($value);
        $slug = preg_replace('/[^a-z0-9]+/', '-', $slug) ?? '';

        return substr(trim($slug, '-'), 0, 60);
    }

    /** RFC 4122 v5 (SHA-1). The same input always yields the same id. */
    private function uuid5(string $name): string
    {
        $namespace = str_replace('-', '', self::NAMESPACE_UUID);
        $bytes = '';
        for ($i = 0; $i < 32; $i += 2) {
            $bytes .= chr((int) hexdec(substr($namespace, $i, 2)));
        }

        $hash = sha1($bytes.$name);

        return sprintf(
            '%08s-%04s-%04x-%04x-%12s',
            substr($hash, 0, 8),
            substr($hash, 8, 4),
            (hexdec(substr($hash, 12, 4)) & 0x0FFF) | 0x5000,
            (hexdec(substr($hash, 16, 4)) & 0x3FFF) | 0x8000,
            substr($hash, 20, 12),
        );
    }
}
